spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carmanagement_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  cloud:
    compatibility-verifier:
      enabled: false  # Helps with Spring Cloud compatibility

  sql:
    init:
      mode: always  # This helps with initial data setup

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost           # Use localhost
    prefer-ip-address: true       # Use IP address
    ip-address: 127.0.0.1         # Explicit IP
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.carmanagement.auth: DEBUG
    org.hibernate.SQL: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.client.discovery: DEBUG

jwt:
  secret: "mySuperSecretKeyForJWTTokenGenerationInCarManagementSystem2024"