spring:
  application:
    name: car-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carmanagement_car
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    compatibility-verifier:
      enabled: false  # Helps with Spring Cloud compatibility

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost           # Use localhost
    prefer-ip-address: true       # Use IP address
    ip-address: 127.0.0.1         # Explicit IP
    instance-id: ${spring.application.name}:${server.port}


car:
  scoring:
    weights:
      usage: 0.4
      recency: 0.3
      price: 0.3
    price:
      thresholds:
        low: 30     # Excellent score
        medium: 60  # Good score
        high: 100   # Average score

logging:
  level:
    com.carmanagement.car: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: "mySuperSecretKeyForJWTTokenGenerationInCarManagementSystem2024"